import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { writeFileSync, unlinkSync, mkdtempSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';

import { FORMATS } from '../src/parsers/index.mjs';

// ---------------------------------------------------------------------------
// FORMATS constant
// ---------------------------------------------------------------------------

describe('FORMATS constant', () => {
  it('exports all expected format identifiers', () => {
    assert.equal(FORMATS.TWENTYTHREE_AND_ME, '23andMe');
    assert.equal(FORMATS.ANCESTRY_DNA, 'AncestryDNA');
    assert.equal(FORMATS.MYHERITAGE, 'MyHeritage');
    assert.equal(FORMATS.FAMILY_TREE_DNA, 'FamilyTreeDNA');
    assert.equal(FORMATS.VCF, 'VCF');
  });
});

// ---------------------------------------------------------------------------
// Parser smoke tests — write minimal valid DNA files and parse them
// ---------------------------------------------------------------------------

describe('23andMe parser', () => {
  it('parses a minimal 23andMe v5 file', async () => {
    const { parse23andMe } = await import('../src/parsers/twentythree-and-me.mjs');
    const dir = mkdtempSync(join(tmpdir(), 'helix-test-'));
    const file = join(dir, 'genome.txt');
    writeFileSync(file, [
      '# This data file generated by 23andMe at: Mon Jan 01 00:00:00 2024',
      '# Build 37',
      '# rsid\tchromosome\tposition\tgenotype',
      'rs4477212\t1\t82154\tAA',
      'rs3094315\t1\t752566\tAA',
      'rs12562034\t1\t768448\tGG',
    ].join('\n'));

    const result = await parse23andMe(file);
    assert.ok(result.genotypes instanceof Map, 'should return a genotypes Map');
    assert.ok(result.genotypes.size >= 3, 'should parse at least 3 variants');
    assert.ok(result.totalCount >= 3, 'totalCount should be set');
    assert.ok(result.version, 'should detect chip version');

    unlinkSync(file);
  });
});

describe('AncestryDNA parser', () => {
  it('parses a minimal AncestryDNA file', async () => {
    const { parseAncestryDna } = await import('../src/parsers/ancestry-dna.mjs');
    const dir = mkdtempSync(join(tmpdir(), 'helix-test-'));
    const file = join(dir, 'AncestryDNA.txt');
    writeFileSync(file, [
      '#AncestryDNA raw data download',
      'rsid\tchromosome\tposition\tallele1\tallele2',
      'rs4477212\t1\t82154\tA\tA',
      'rs3094315\t1\t752566\tA\tA',
      'rs12562034\t1\t768448\tG\tG',
    ].join('\n'));

    const result = await parseAncestryDna(file);
    assert.ok(result.genotypes instanceof Map, 'should return a genotypes Map');
    assert.ok(result.genotypes.size >= 3, 'should parse at least 3 variants');
    assert.ok(result.genotypes.has('rs4477212'), 'should have rs4477212');

    unlinkSync(file);
  });
});

describe('VCF parser', () => {
  it('parses a minimal VCF 4.1 file', async () => {
    const { parseVcf } = await import('../src/parsers/vcf.mjs');
    const dir = mkdtempSync(join(tmpdir(), 'helix-test-'));
    const file = join(dir, 'sample.vcf');
    writeFileSync(file, [
      '##fileformat=VCFv4.1',
      '##FILTER=<ID=PASS,Description="All filters passed">',
      '#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tSAMPLE',
      '1\t82154\trs4477212\tA\tG\t.\tPASS\t.\tGT\t0/0',
      '1\t752566\trs3094315\tG\tA\t.\tPASS\t.\tGT\t0/1',
    ].join('\n'));

    const result = await parseVcf(file);
    assert.ok(result.genotypes instanceof Map, 'should return a genotypes Map');
    assert.ok(result.genotypes.size >= 1, 'should parse at least 1 variant');

    unlinkSync(file);
  });
});
