/**
 * DNA file parser dispatcher
 *
 * Auto-detects file format from the first 20 lines of the file,
 * dispatches to the correct parser, and returns a unified result object.
 *
 * Supported formats:
 *   - 23andMe (v3, v4, v5)
 *   - AncestryDNA
 *   - MyHeritage
 *   - FamilyTreeDNA (FTDNA)
 *   - VCF 4.x (chip and WGS)
 */

import { createReadStream, readFileSync, writeFileSync, mkdtempSync, unlinkSync, existsSync } from 'node:fs';
import { createInterface } from 'node:readline';
import { basename, join } from 'node:path';
import { stat } from 'node:fs/promises';
import { gunzipSync } from 'node:zlib';
import { tmpdir } from 'node:os';
import AdmZip from 'adm-zip';

import { parse23andMe } from './twentythree-and-me.mjs';
import { parseAncestryDna } from './ancestry-dna.mjs';
import { parseMyHeritage } from './myheritage.mjs';
import { parseFamilyTreeDna } from './familytreedna.mjs';
import { parseVcf } from './vcf.mjs';

/** Known format identifiers. */
export const FORMATS = {
  TWENTYTHREE_AND_ME: '23andMe',
  ANCESTRY_DNA: 'AncestryDNA',
  MYHERITAGE: 'MyHeritage',
  FAMILY_TREE_DNA: 'FamilyTreeDNA',
  VCF: 'VCF',
};

/**
 * Read the first N lines of a file for format detection.
 *
 * @param {string} filePath - Path to the file.
 * @param {number} [maxLines=20] - Number of lines to read.
 * @returns {Promise<string[]>} The first N lines.
 */
async function readFirstLines(filePath, maxLines = 20) {
  const lines = [];
  const rl = createInterface({
    input: createReadStream(filePath, { encoding: 'utf8' }),
    crlfDelay: Infinity,
  });

  for await (const line of rl) {
    lines.push(line);
    if (lines.length >= maxLines) break;
  }

  // Close the stream explicitly to avoid holding the file handle
  rl.close();
  return lines;
}

/**
 * Detect the DNA file format from header lines.
 *
 * Detection priority:
 *   1. Content-based detection from first 20 lines
 *   2. Filename-based fallback
 *
 * @param {string[]} headerLines - First 20 lines of the file.
 * @param {string} fileName - The file's basename (for fallback detection).
 * @returns {{ format: string|null, confidence: 'high'|'medium'|'low' }}
 */
function detectFormat(headerLines, fileName) {
  const joined = headerLines.join('\n');
  const joinedLower = joined.toLowerCase();

  // --- Content-based detection (high confidence) ---

  // 23andMe: distinctive header comment
  if (joined.includes('# This data file generated by 23andMe') ||
      joined.includes('#23andMe')) {
    return { format: FORMATS.TWENTYTHREE_AND_ME, confidence: 'high' };
  }

  // AncestryDNA: distinctive header comment
  if (joined.includes('#AncestryDNA') || joined.includes('# AncestryDNA')) {
    return { format: FORMATS.ANCESTRY_DNA, confidence: 'high' };
  }

  // VCF: standard file format declaration
  if (joined.includes('##fileformat=VCF') || joined.includes('##fileformat=vcf')) {
    return { format: FORMATS.VCF, confidence: 'high' };
  }

  // --- Column-header-based detection (medium confidence) ---

  // Look for data lines (skip comments) and check structure
  for (const line of headerLines) {
    if (line.startsWith('#') || !line.trim()) continue;

    const lower = line.toLowerCase().replace(/"/g, '');

    // MyHeritage / FTDNA CSV header: RSID,CHROMOSOME,POSITION,RESULT
    if (lower.includes('rsid') && lower.includes('chromosome') &&
        lower.includes('position') && lower.includes('result')) {
      // Distinguish MyHeritage from FTDNA by comma vs tab
      if (line.includes(',')) {
        // Could be either; check filename for disambiguation
        const fileNameLower = fileName.toLowerCase();
        if (fileNameLower.includes('ftdna') || fileNameLower.includes('familytree') ||
            fileNameLower.includes('family_tree')) {
          return { format: FORMATS.FAMILY_TREE_DNA, confidence: 'medium' };
        }
        if (fileNameLower.includes('myheritage')) {
          return { format: FORMATS.MYHERITAGE, confidence: 'medium' };
        }
        // Default to MyHeritage for comma-separated RSID,CHROMOSOME,POSITION,RESULT
        return { format: FORMATS.MYHERITAGE, confidence: 'medium' };
      }
      if (line.includes('\t')) {
        return { format: FORMATS.FAMILY_TREE_DNA, confidence: 'medium' };
      }
    }

    // AncestryDNA tab-separated: rsid, chromosome, position, allele1, allele2
    if (lower.includes('rsid') && lower.includes('allele1') && lower.includes('allele2')) {
      return { format: FORMATS.ANCESTRY_DNA, confidence: 'medium' };
    }

    // 23andMe data line pattern: rsid \t chr \t pos \t genotype (4 tab-separated fields)
    const tabParts = line.split('\t');
    if (tabParts.length === 4) {
      const possibleRsid = tabParts[0].trim();
      const possibleChr = tabParts[1].trim();
      const possiblePos = tabParts[2].trim();
      const possibleGeno = tabParts[3].trim();

      if ((possibleRsid.startsWith('rs') || possibleRsid.startsWith('i')) &&
          /^\d{1,2}|[XYM]/.test(possibleChr) &&
          /^\d+$/.test(possiblePos) &&
          possibleGeno.length <= 4) {
        return { format: FORMATS.TWENTYTHREE_AND_ME, confidence: 'medium' };
      }
    }

    // If it's the first data line, stop looking
    break;
  }

  // --- Filename-based fallback (low confidence) ---
  const fileNameLower = fileName.toLowerCase();

  if (fileNameLower.includes('23andme') || fileNameLower.includes('23_and_me')) {
    return { format: FORMATS.TWENTYTHREE_AND_ME, confidence: 'low' };
  }
  if (fileNameLower.includes('ancestry') || fileNameLower.includes('ancestrydna')) {
    return { format: FORMATS.ANCESTRY_DNA, confidence: 'low' };
  }
  if (fileNameLower.includes('myheritage') || fileNameLower.includes('my_heritage')) {
    return { format: FORMATS.MYHERITAGE, confidence: 'low' };
  }
  if (fileNameLower.includes('ftdna') || fileNameLower.includes('familytree') ||
      fileNameLower.includes('family_tree')) {
    return { format: FORMATS.FAMILY_TREE_DNA, confidence: 'low' };
  }
  if (fileNameLower.endsWith('.vcf') || fileNameLower.endsWith('.vcf.gz')) {
    return { format: FORMATS.VCF, confidence: 'low' };
  }

  return { format: null, confidence: 'low' };
}

/**
 * Detect chip version for 23andMe files.
 * Rough heuristic based on genotype count.
 */
function detect23andMeVersion(count, parserVersion) {
  if (parserVersion && parserVersion !== 'unknown') return parserVersion;
  if (count > 900000) return 'v5';   // v5 chip: ~960K SNPs
  if (count > 700000) return 'v4';   // v4 chip: ~750K SNPs
  if (count > 500000) return 'v3';   // v3 chip: ~600K SNPs
  return 'unknown';
}

/**
 * Parse a DNA file with auto-format detection.
 *
 * @param {string} filePath - Absolute path to the DNA data file.
 * @param {string} [forceFormat] - Force a specific format instead of auto-detecting.
 *   Valid values: '23andMe', 'AncestryDNA', 'MyHeritage', 'FamilyTreeDNA', 'VCF'
 * @param {object} [options] - Options passed through to the individual parser.
 * @param {boolean} [options.skipMT=false] - Skip mitochondrial variants.
 * @param {boolean} [options.skipY=false] - Skip Y chromosome variants.
 * @param {boolean} [options.rsidOnly=true] - VCF only: skip variants without rs IDs.
 * @param {function} [options.onProgress] - Progress callback(lineCount).
 * @returns {Promise<{format: string, version: string|null, count: number, genotypes: Map, noCallRate: number, metadata: {headerLines: string[], build: string|null}}>}
 */

/**
 * Extract a DNA file from a .zip or .gz archive to a temp file.
 * Returns the path to the extracted file (caller must clean up).
 * Returns null if the file is not an archive.
 */
function extractArchive(filePath) {
  const lower = filePath.toLowerCase();

  if (lower.endsWith('.gz')) {
    const compressed = readFileSync(filePath);
    const decompressed = gunzipSync(compressed);
    const tmpDir = mkdtempSync(join(tmpdir(), 'helix-'));
    const outName = basename(filePath).replace(/\.gz$/i, '');
    const outPath = join(tmpDir, outName);
    writeFileSync(outPath, decompressed);
    console.log(`[parser] Decompressed .gz: ${basename(filePath)} -> ${outName}`);
    return outPath;
  }

  if (lower.endsWith('.zip')) {
    const zip = new AdmZip(filePath);
    const entries = zip.getEntries().filter(
      e => !e.isDirectory && /\.(txt|csv|tsv|vcf)$/i.test(e.entryName)
    );
    if (entries.length === 0) {
      throw new Error(
        'No DNA data file found inside the zip archive. ' +
        'Expected a .txt, .csv, .tsv, or .vcf file inside the zip.'
      );
    }
    // Use the largest matching file (most likely the actual data)
    entries.sort((a, b) => b.header.size - a.header.size);
    const entry = entries[0];
    const tmpDir = mkdtempSync(join(tmpdir(), 'helix-'));
    const outPath = join(tmpDir, basename(entry.entryName));
    writeFileSync(outPath, entry.getData());
    console.log(
      `[parser] Extracted from zip: ${entry.entryName} ` +
      `(${(entry.header.size / 1024 / 1024).toFixed(1)} MB)`
    );
    return outPath;
  }

  return null;
}

export async function parseDnaFile(filePath, forceFormat, options = {}) {
  // Handle case where second arg is options object (no forceFormat)
  if (typeof forceFormat === 'object' && forceFormat !== null) {
    options = forceFormat;
    forceFormat = undefined;
  }

  // Extract from archive if needed (.zip, .gz)
  let extractedPath = null;
  try {
    extractedPath = extractArchive(filePath);
  } catch (err) {
    throw new Error(`Failed to extract archive: ${err.message}`);
  }
  const actualPath = extractedPath || filePath;

  // Verify file exists and is readable
  let fileStat;
  try {
    fileStat = await stat(actualPath);
  } catch (err) {
    if (extractedPath) try { unlinkSync(extractedPath); } catch {}
    throw new Error(`Cannot access DNA file: ${actualPath} (${err.code || err.message})`);
  }

  if (!fileStat.isFile()) {
    if (extractedPath) try { unlinkSync(extractedPath); } catch {}
    throw new Error(`Path is not a file: ${actualPath}`);
  }

  const fileName = basename(extractedPath ? filePath : actualPath);
  const fileSizeMB = (fileStat.size / 1024 / 1024).toFixed(1);

  // Determine format
  let format;
  let confidence;

  if (forceFormat) {
    // Validate the forced format
    const validFormats = Object.values(FORMATS);
    if (!validFormats.includes(forceFormat)) {
      throw new Error(
        `Unknown format "${forceFormat}". ` +
        `Valid formats: ${validFormats.join(', ')}`
      );
    }
    format = forceFormat;
    confidence = 'forced';
  } else {
    // Auto-detect from first 20 lines
    const firstLines = await readFirstLines(actualPath, 20);
    if (firstLines.length === 0) {
      throw new Error(`File is empty: ${actualPath}`);
    }
    const detection = detectFormat(firstLines, fileName);
    format = detection.format;
    confidence = detection.confidence;

    if (!format) {
      throw new Error(
        `Unable to detect DNA file format for ${fileName}. ` +
        `The file does not match any known format (23andMe, AncestryDNA, MyHeritage, FamilyTreeDNA, VCF). ` +
        `You can use the forceFormat parameter to specify the format manually.`
      );
    }
  }

  console.log(
    `[parser] Detected format: ${format} (confidence: ${confidence}) ` +
    `| File: ${fileName} (${fileSizeMB} MB)`
  );

  // Dispatch to the correct parser
  let result;
  const startTime = Date.now();

  switch (format) {
    case FORMATS.TWENTYTHREE_AND_ME:
      result = await parse23andMe(actualPath, options);
      break;

    case FORMATS.ANCESTRY_DNA:
      result = await parseAncestryDna(actualPath, options);
      break;

    case FORMATS.MYHERITAGE:
      result = await parseMyHeritage(actualPath, options);
      break;

    case FORMATS.FAMILY_TREE_DNA:
      result = await parseFamilyTreeDna(actualPath, options);
      break;

    case FORMATS.VCF:
      result = await parseVcf(actualPath, options);
      break;

    default:
      throw new Error(`No parser implemented for format: ${format}`);
  }

  const elapsed = ((Date.now() - startTime) / 1000).toFixed(2);

  // Build unified output
  const genotypes = result.genotypes;
  const totalCount = result.totalCount;
  const noCallCount = result.noCallCount;
  const noCallRate = totalCount > 0 ? noCallCount / totalCount : 0;

  // Determine version
  let version = null;
  if (format === FORMATS.TWENTYTHREE_AND_ME) {
    version = detect23andMeVersion(genotypes.size, result.version);
  } else if (format === FORMATS.VCF) {
    version = result.vcfVersion ? `VCF ${result.vcfVersion}` : null;
  }

  // Determine build
  const build = result.build || null;

  // Collect header/metadata lines
  const headerLines = result.headerLines || result.metadataLines || [];

  console.log(
    `[parser] Parsed ${genotypes.size.toLocaleString()} genotypes ` +
    `(${noCallCount.toLocaleString()} no-calls, ${(noCallRate * 100).toFixed(1)}% no-call rate) ` +
    `in ${elapsed}s`
  );

  // Clean up extracted temp file
  if (extractedPath) {
    try { unlinkSync(extractedPath); } catch {}
  }

  return {
    format,
    version,
    count: genotypes.size,
    genotypes,
    noCallRate: Math.round(noCallRate * 10000) / 10000, // 4 decimal places
    metadata: {
      headerLines,
      build,
      sampleName: result.sampleName || null,
      fileName,
      fileSizeMB: parseFloat(fileSizeMB),
      parseTimeSeconds: parseFloat(elapsed),
      detectionConfidence: confidence,
    },
  };
}
