/**
 * 23andMe raw data parser
 * Supports v3 (headerless), v4, and v5 (with header row) formats.
 *
 * File format:
 *   # Comment/metadata lines
 *   rsid \t chromosome \t position \t genotype
 *
 * Genotype values: two-letter alleles (AA, AG, etc.),
 *   -- (no-call), I/D/II/DD/DI (indels), single letter for chrX/chrY hemizygous.
 */

import { createReadStream } from 'node:fs';
import { createInterface } from 'node:readline';

const VALID_CHROMOSOMES = new Set([
  '1','2','3','4','5','6','7','8','9','10',
  '11','12','13','14','15','16','17','18','19','20',
  '21','22','X','Y','MT',
]);

/**
 * Detect chip version from header comments.
 * v5 files include "# This data file generated by 23andMe" with build 37.
 * v3 files are older, often build 36. v4 is intermediate.
 */
function detectVersion(headerLines) {
  const joined = headerLines.join('\n').toLowerCase();

  if (joined.includes('build 37') || joined.includes('grch37')) {
    // v5 uses GRCh37, often has a header row
    return 'v5';
  }
  if (joined.includes('build 36') || joined.includes('ncbi36')) {
    return 'v3';
  }
  // v4 is less common; check for platform info
  if (joined.includes('platform v4') || joined.includes('v4')) {
    return 'v4';
  }
  // Default to v5 if we see the standard 23andMe header
  if (joined.includes('23andme')) {
    return 'v5';
  }
  return 'unknown';
}

/**
 * Detect genome build from header comments.
 */
function detectBuild(headerLines) {
  const joined = headerLines.join('\n').toLowerCase();
  if (joined.includes('build 37') || joined.includes('grch37')) return 'GRCh37';
  if (joined.includes('build 38') || joined.includes('grch38')) return 'GRCh38';
  if (joined.includes('build 36') || joined.includes('ncbi36')) return 'NCBI36';
  return null;
}

/**
 * Normalize genotype value.
 * Returns null for no-calls (--).
 */
function normalizeGenotype(raw) {
  if (!raw || raw === '--' || raw === '..') return null;
  return raw.toUpperCase();
}

/**
 * Parse a 23andMe raw data file.
 *
 * @param {string} filePath - Absolute path to the raw data file.
 * @param {object} [options] - Parsing options.
 * @param {boolean} [options.skipMT=false] - Skip mitochondrial variants.
 * @param {boolean} [options.skipY=false] - Skip Y chromosome variants.
 * @param {function} [options.onProgress] - Callback(lineCount) for progress updates.
 * @returns {Promise<{genotypes: Map, headerLines: string[], version: string, build: string|null, noCallCount: number, totalCount: number}>}
 */
export async function parse23andMe(filePath, options = {}) {
  const { skipMT = false, skipY = false, onProgress } = options;

  const genotypes = new Map();
  const headerLines = [];
  let totalCount = 0;
  let noCallCount = 0;
  let lineNumber = 0;
  let hasHeaderRow = false;
  const progressInterval = 100000;

  const rl = createInterface({
    input: createReadStream(filePath, { encoding: 'utf8' }),
    crlfDelay: Infinity,
  });

  for await (const line of rl) {
    lineNumber++;

    // Skip empty lines
    if (!line.trim()) continue;

    // Collect comment/metadata lines
    if (line.startsWith('#')) {
      headerLines.push(line);
      continue;
    }

    // Detect and skip header row (v5 format): "rsid\tchromosome\tposition\tgenotype"
    const lower = line.toLowerCase();
    if (lower.startsWith('rsid') && lower.includes('chromosome')) {
      hasHeaderRow = true;
      continue;
    }

    // Parse data line: rsid \t chr \t pos \t genotype
    const parts = line.split('\t');
    if (parts.length < 4) {
      // Some files use spaces or mixed delimiters; try splitting on whitespace
      const spaceParts = line.trim().split(/\s+/);
      if (spaceParts.length >= 4) {
        parts.length = 0;
        parts.push(...spaceParts);
      } else {
        continue; // Skip malformed lines
      }
    }

    const rsid = parts[0].trim();
    const chromosome = parts[1].trim().toUpperCase().replace('CHR', '');
    const position = parseInt(parts[2].trim(), 10);
    const rawGenotype = parts[3].trim();

    // Validate chromosome
    if (!VALID_CHROMOSOMES.has(chromosome)) continue;

    // Apply chromosome filters
    if (skipMT && chromosome === 'MT') continue;
    if (skipY && chromosome === 'Y') continue;

    // Validate position
    if (isNaN(position) || position <= 0) continue;

    // Validate rsid format (rs*, i*, or internal IDs)
    if (!rsid) continue;

    totalCount++;

    const genotype = normalizeGenotype(rawGenotype);
    if (genotype === null) {
      noCallCount++;
      // Still store no-calls so we track them
      genotypes.set(rsid, {
        rsid,
        chromosome,
        position,
        genotype: '--',
      });
    } else {
      genotypes.set(rsid, {
        rsid,
        chromosome,
        position,
        genotype,
      });
    }

    // Progress reporting
    if (onProgress && lineNumber % progressInterval === 0) {
      onProgress(lineNumber);
    }
  }

  const version = detectVersion(headerLines);
  const build = detectBuild(headerLines);

  if (totalCount === 0) {
    throw new Error(
      `23andMe parser: No valid genotype lines found in ${filePath}. ` +
      `Read ${lineNumber} lines total, ${headerLines.length} comment lines.`
    );
  }

  return {
    genotypes,
    headerLines,
    version,
    build,
    noCallCount,
    totalCount,
    hasHeaderRow,
  };
}
